baseURL = 'https://chrisdotslash.github.io/'
languageCode = 'en-us'
title = 'chris./'
theme = 'hugo-PaperMod'
favicon = '/assets/chrisdotslash_logo.png'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]

# Main menu
[[menus.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menus.main]]
name = "About"
pageRef = "/about"
weight = 20

[[menus.main]]
name = "Projects"
pageRef = "/projects"
weight = 30

[[menus.main]]
name = "Reading"
pageRef = "/reading"
weight = 40

[[menus.main]]
name = "Learning"
pageRef = "/learning"
weight = 50

[[menus.main]]
name = "Contact"
pageRef = "/contact"
weight = 60
