baseURL = 'https://chriseborowski.github.io/mypage/'
languageCode = 'en-us'
title = 'Chris Borowski'
theme = 'hugo-PaperMod'
favicon = 'https://github.com/chriseborowski/chriseborowski.github.io/blob/main/static/favicon.ico'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]

# Main menu
[[menus.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menus.main]]
name = "About"
pageRef = "/about"
weight = 20

[[menus.main]]
name = "Projects"
pageRef = "/projects"
weight = 30

[[menus.main]]
name = "Reading"
pageRef = "/reading"
weight = 40

[[menus.main]]
name = "Learning"
pageRef = "/learning"
weight = 50

[[menus.main]]
name = "Contact"
pageRef = "/contact"
weight = 60
